<?php
/*
* This FIle was automatically generated By Path
* Modify to your advantage
*/

namespace Path\App\Database\Migration;


use Path\Core\Database\Model;
use Path\Core\Database\Prototype;
use Path\Core\Database\Structure;
use Path\Core\Database\Table;



class Profile implements Table
{
    public $table_name = "profile";
    public $primary_key = "id";
    public function install(Structure &$table)
    {

        $table->column('age')
            ->type('VARCHAR(255)')
            ->nullable();

        $table->column('gender')
            ->type('VARCHAR(255)')
            ->nullable();

        $table->column('about')
            ->type('VARCHAR(255)')
            ->nullable();

        $table->column('name')
            ->type('VARCHAR(255)')
            ->nullable();


    }

    public function uninstall()
    {
    }

    public function populate(Model $table)
    {

    }

    public function update(Structure &$table)
    {
        $table->column('handle')
            ->type('VARCHAR(255)')
            ->nullable();
    }
}