<?php
/*
* This FIle was automatically generated By Path
* Modify to your advantage
*/

namespace Path\App\Database\Migration;


use Path\Core\Database\Model;
use Path\Core\Database\Prototype;
use Path\Core\Database\Structure;
use Path\Core\Database\Table;



class User implements Table
{
    public $table_name = "user";
    public $primary_key = "id";
    public function install(Structure &$table)
    {
        $table->column('email')
            ->type('VARCHAR(255)')
            ->nullable();

        $table->column('handle')
            ->type('VARCHAR(255)')
            ->nullable();

        $table->column('profile_id')
            ->type('INT')
            ->references('profile(id)');

    }

    public function uninstall()
    {
    }

    public function populate(Model $table)
    {

    }

    public function update(Structure &$table)
    {


    }
}